import { BlockDef, BlockType, CraftingRecipe, DailyQuest, InventoryItem, NPC, Quest, ToolType } from '../types/game';

export const BLOCK_DEFINITIONS: Record<BlockType, BlockDef> = {
  GRASS: {
    id: 'GRASS',
    name: 'Grass Block',
    color: 0x55ab38,
    topColor: 0x64c942,
    sideColor: 0x68523c,
    hardness: 0.8,
    preferredTool: 'SHOVEL',
    icon: '🌱',
    category: 'terrain',
  },
  DIRT: {
    id: 'DIRT',
    name: 'Cozy Dirt',
    color: 0x68523c,
    topColor: 0x7a6148,
    sideColor: 0x5a4633,
    hardness: 0.7,
    preferredTool: 'SHOVEL',
    icon: '🟫',
    category: 'terrain',
  },
  STONE: {
    id: 'STONE',
    name: 'Grey Rock Stone',
    color: 0x828891,
    topColor: 0x939aa3,
    sideColor: 0x717780,
    hardness: 1.8,
    preferredTool: 'PICKAXE',
    icon: '🪨',
    category: 'terrain',
  },
  WATER: {
    id: 'WATER',
    name: 'Crystal Water',
    color: 0x3b82f6,
    topColor: 0x60a5fa,
    sideColor: 0x2563eb,
    transparent: true,
    isFluid: true,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '💧',
    category: 'terrain',
  },
  SAND: {
    id: 'SAND',
    name: 'River Sand',
    color: 0xeed690,
    topColor: 0xf5df9d,
    sideColor: 0xd9c179,
    hardness: 0.6,
    preferredTool: 'SHOVEL',
    icon: '🏖️',
    category: 'terrain',
  },
  WOOD_LOG: {
    id: 'WOOD_LOG',
    name: 'Oak Timber Log',
    color: 0x614835,
    topColor: 0x967856,
    sideColor: 0x543e2e,
    hardness: 1.5,
    preferredTool: 'AXE',
    icon: '🪵',
    category: 'building',
  },
  LEAVES: {
    id: 'LEAVES',
    name: 'Pine Leaves',
    color: 0x1f7a2d,
    topColor: 0x289938,
    sideColor: 0x196324,
    hardness: 0.4,
    preferredTool: 'HAND',
    icon: '🌲',
    category: 'nature',
  },
  PLANKS: {
    id: 'PLANKS',
    name: 'Wooden Planks',
    color: 0xb58957,
    topColor: 0xc99a63,
    sideColor: 0xa3794a,
    hardness: 1.2,
    preferredTool: 'AXE',
    icon: '🪚',
    category: 'building',
  },
  COBBLESTONE: {
    id: 'COBBLESTONE',
    name: 'Village Cobblestone',
    color: 0x69717d,
    topColor: 0x7c8591,
    sideColor: 0x585f69,
    hardness: 2.0,
    preferredTool: 'PICKAXE',
    icon: '🧱',
    category: 'building',
  },
  BRICK: {
    id: 'BRICK',
    name: 'Red Clay Brick',
    color: 0xa84832,
    topColor: 0xc2563c,
    sideColor: 0x8f3c29,
    hardness: 2.2,
    preferredTool: 'PICKAXE',
    icon: '🏮',
    category: 'building',
  },
  WALL_BEIGE: {
    id: 'WALL_BEIGE',
    name: 'Beige House Wall',
    color: 0xe6dbc8,
    topColor: 0xf2e8d5,
    sideColor: 0xd4c8b4,
    hardness: 1.5,
    preferredTool: 'PICKAXE',
    icon: '🏠',
    category: 'building',
  },
  WALL_WHITE: {
    id: 'WALL_WHITE',
    name: 'White Stucco Wall',
    color: 0xf8fafc,
    topColor: 0xffffff,
    sideColor: 0xe2e8f0,
    hardness: 1.5,
    preferredTool: 'PICKAXE',
    icon: '⬜',
    category: 'building',
  },
  WALL_STONE: {
    id: 'WALL_STONE',
    name: 'Chiseled Stone Wall',
    color: 0x475569,
    topColor: 0x64748b,
    sideColor: 0x334155,
    hardness: 2.0,
    preferredTool: 'PICKAXE',
    icon: '🧱',
    category: 'building',
  },
  ROOF_BROWN: {
    id: 'ROOF_BROWN',
    name: 'Brown Shingle Roof',
    color: 0x6e4328,
    topColor: 0x825132,
    sideColor: 0x5c361e,
    hardness: 1.5,
    preferredTool: 'AXE',
    icon: '⛺',
    category: 'building',
  },
  ROOF_RED: {
    id: 'ROOF_RED',
    name: 'Terracotta Red Roof',
    color: 0x991b1b,
    topColor: 0xb91c1c,
    sideColor: 0x7f1d1d,
    hardness: 1.5,
    preferredTool: 'PICKAXE',
    icon: '🏠',
    category: 'building',
  },
  ROOF_BLUE: {
    id: 'ROOF_BLUE',
    name: 'Slate Blue Roof',
    color: 0x1e3a8a,
    topColor: 0x2563eb,
    sideColor: 0x172554,
    hardness: 1.5,
    preferredTool: 'PICKAXE',
    icon: '🏠',
    category: 'building',
  },
  ROOF_DARK: {
    id: 'ROOF_DARK',
    name: 'Dark Slate Roof',
    color: 0x0f172a,
    topColor: 0x1e293b,
    sideColor: 0x020617,
    hardness: 1.5,
    preferredTool: 'PICKAXE',
    icon: '🏠',
    category: 'building',
  },
  FENCE: {
    id: 'FENCE',
    name: 'Wooden Fence',
    color: 0x855f38,
    hardness: 1.0,
    preferredTool: 'AXE',
    icon: '🚧',
    category: 'decoration',
    isCustomMesh: 'fence',
  },
  FLOWER: {
    id: 'FLOWER',
    name: 'Wild Meadow Flower',
    color: 0xffe135,
    hardness: 0.2,
    preferredTool: 'HAND',
    icon: '🌼',
    category: 'nature',
    isCustomMesh: 'flower',
  },
  LAMP: {
    id: 'LAMP',
    name: 'Village Lantern',
    color: 0xfacc15,
    hardness: 1.0,
    preferredTool: 'PICKAXE',
    icon: '🏮',
    category: 'decoration',
    lightEmission: 1.0,
    isCustomMesh: 'lamp',
  },
  CAUTION_TAPE: {
    id: 'CAUTION_TAPE',
    name: 'Caution Barricade',
    color: 0xfacc15,
    hardness: 0.5,
    preferredTool: 'HAND',
    icon: '⚠️',
    category: 'decoration',
    isCustomMesh: 'caution',
  },
  TABLE_WOOD: {
    id: 'TABLE_WOOD',
    name: 'Village Square Table',
    color: 0x6e4826,
    hardness: 1.5,
    preferredTool: 'AXE',
    icon: '🪑',
    category: 'decoration',
    isCustomMesh: 'table',
  },
  GOLD_ORE: {
    id: 'GOLD_ORE',
    name: 'Glittering Gold Ore',
    color: 0xf59e0b,
    topColor: 0xfbbf24,
    sideColor: 0xd97706,
    hardness: 2.5,
    preferredTool: 'PICKAXE',
    icon: '✨',
    category: 'terrain',
    isCustomMesh: 'gold',
  },
  COAL_ORE: {
    id: 'COAL_ORE',
    name: 'Black Coal Deposit',
    color: 0x334155,
    topColor: 0x475569,
    sideColor: 0x1e293b,
    hardness: 1.8,
    preferredTool: 'PICKAXE',
    icon: '⬛',
    category: 'terrain',
    isCustomMesh: 'coal',
  },
  IRON_ORE: {
    id: 'IRON_ORE',
    name: 'Rich Iron Vein',
    color: 0x94a3b8,
    topColor: 0xcbaf87,
    sideColor: 0x64748b,
    hardness: 2.2,
    preferredTool: 'PICKAXE',
    icon: '🪨',
    category: 'terrain',
    isCustomMesh: 'iron',
  },
  CRYSTAL_ORE: {
    id: 'CRYSTAL_ORE',
    name: 'Glowing Mana Crystal',
    color: 0x38bdf8,
    topColor: 0x7dd3fc,
    sideColor: 0x0284c7,
    hardness: 3.0,
    preferredTool: 'PICKAXE',
    icon: '💎',
    category: 'terrain',
    lightEmission: 0.8,
    isCustomMesh: 'crystal',
  },
  HERB: {
    id: 'HERB',
    name: 'Healing Wild Herb',
    color: 0x10b981,
    hardness: 0.2,
    preferredTool: 'HAND',
    icon: '🌿',
    category: 'nature',
    isCustomMesh: 'herb',
  },
  BERRY_BUSH: {
    id: 'BERRY_BUSH',
    name: 'Wild Berry Bush',
    color: 0xe11d48,
    hardness: 0.3,
    preferredTool: 'HAND',
    icon: '🍓',
    category: 'nature',
    isCustomMesh: 'berry',
  },
  MUSHROOM: {
    id: 'MUSHROOM',
    name: 'Red Cap Mushroom',
    color: 0xdc2626,
    hardness: 0.2,
    preferredTool: 'HAND',
    icon: '🍄',
    category: 'nature',
    isCustomMesh: 'mushroom',
  },
  TREASURE_CHEST: {
    id: 'TREASURE_CHEST',
    name: 'Buried Treasure Chest',
    color: 0xd97706,
    hardness: 1.5,
    preferredTool: 'SHOVEL',
    icon: '🪙',
    category: 'decoration',
    isCustomMesh: 'chest',
  },
  CROPS: {
    id: 'CROPS',
    name: 'Wheat Wheatland',
    color: 0xeab308,
    hardness: 0.3,
    preferredTool: 'HAND',
    icon: '🌾',
    category: 'nature',
    isCustomMesh: 'crops',
  },
  BENCH: {
    id: 'BENCH',
    name: 'Wooden Park Bench',
    color: 0x78350f,
    hardness: 0.8,
    preferredTool: 'AXE',
    icon: '🪑',
    category: 'decoration',
    isCustomMesh: 'bench',
  },
  LOG_SEAT: {
    id: 'LOG_SEAT',
    name: 'Log Seat',
    color: 0x92400e,
    hardness: 0.8,
    preferredTool: 'AXE',
    icon: '🪵',
    category: 'decoration',
    isCustomMesh: 'log_seat',
  },
  BBQ_GRILL: {
    id: 'BBQ_GRILL',
    name: 'BBQ Grill',
    color: 0x334155,
    hardness: 1.0,
    preferredTool: 'PICKAXE',
    icon: '🍖',
    category: 'decoration',
    isCustomMesh: 'bbq',
  },
  CIRCUS_TENT: {
    id: 'CIRCUS_TENT',
    name: 'Grand Circus Tent',
    color: 0xef4444,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🎪',
    category: 'building',
    isCustomMesh: 'circus',
  },
  FERRIS_WHEEL: {
    id: 'FERRIS_WHEEL',
    name: 'Ferris Wheel',
    color: 0x3b82f6,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🎡',
    category: 'building',
    isCustomMesh: 'ferris',
  },
  MERRY_GO_ROUND: {
    id: 'MERRY_GO_ROUND',
    name: 'Carousel Merry-Go-Round',
    color: 0xf59e0b,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🎠',
    category: 'building',
    isCustomMesh: 'merry',
  },
  ICE_CREAM_CART: {
    id: 'ICE_CREAM_CART',
    name: 'Ice Cream Cart',
    color: 0xec4899,
    hardness: 1.0,
    preferredTool: 'HAND',
    icon: '🍦',
    category: 'decoration',
    isCustomMesh: 'icecream',
  },
  BALLOON_STAND: {
    id: 'BALLOON_STAND',
    name: 'Balloon Stand',
    color: 0x8b5cf6,
    hardness: 1.0,
    preferredTool: 'HAND',
    icon: '🎈',
    category: 'decoration',
    isCustomMesh: 'balloon',
  },
  WATERFALL: {
    id: 'WATERFALL',
    name: 'Cascading Waterfall',
    color: 0x38bdf8,
    transparent: true,
    isFluid: true,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🌊',
    category: 'terrain',
    isCustomMesh: 'waterfall',
  },
  BEEHIVE: {
    id: 'BEEHIVE',
    name: 'Honey Beehive',
    color: 0xf59e0b,
    hardness: 0.5,
    preferredTool: 'HAND',
    icon: '🐝',
    category: 'nature',
    isCustomMesh: 'beehive',
  },
  COW: {
    id: 'COW',
    name: 'Farm Cow',
    color: 0xffffff,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐄',
    category: 'nature',
    isCustomMesh: 'cow',
  },
  CHICKEN: {
    id: 'CHICKEN',
    name: 'Farm Chicken',
    color: 0xfef08a,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐔',
    category: 'nature',
    isCustomMesh: 'chicken',
  },
  SHEEP: {
    id: 'SHEEP',
    name: 'Fluffy Sheep',
    color: 0xf8fafc,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐑',
    category: 'nature',
    isCustomMesh: 'sheep',
  },
  HORSE: {
    id: 'HORSE',
    name: 'Stable Horse',
    color: 0xb45309,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐎',
    category: 'nature',
    isCustomMesh: 'horse',
  },
  GOAT: {
    id: 'GOAT',
    name: 'Mountain Goat',
    color: 0xe2e8f0,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐐',
    category: 'nature',
    isCustomMesh: 'goat',
  },
  RABBIT: {
    id: 'RABBIT',
    name: 'Wild Rabbit',
    color: 0xd97706,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐇',
    category: 'nature',
    isCustomMesh: 'rabbit',
  },
  DEER: {
    id: 'DEER',
    name: 'Forest Deer',
    color: 0x92400e,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🦌',
    category: 'nature',
    isCustomMesh: 'deer',
  },
  DUCK: {
    id: 'DUCK',
    name: 'Pond Duck',
    color: 0x15803d,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🦆',
    category: 'nature',
    isCustomMesh: 'duck',
  },
  DOG: {
    id: 'DOG',
    name: 'Friendly Dog',
    color: 0xd97706,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐕',
    category: 'nature',
    isCustomMesh: 'dog',
  },
  CAT: {
    id: 'CAT',
    name: 'Rooftop Cat',
    color: 0xf97316,
    hardness: 999,
    preferredTool: 'HAND',
    icon: '🐈',
    category: 'nature',
    isCustomMesh: 'cat',
  },
  BOXING_RING: {
    id: 'BOXING_RING', name: 'Open-Air Boxing Ring', color: 0xdc2626, hardness: 999, preferredTool: 'HAND', icon: '🥊', category: 'building', isCustomMesh: 'ring',
  },
  SMALL_POND: {
    id: 'SMALL_POND', name: 'Lily Pond', color: 0x38bdf8, transparent: true, isFluid: true, hardness: 999, preferredTool: 'HAND', icon: '🪷', category: 'terrain', isCustomMesh: 'pond',
  },
  WINDMILL: {
    id: 'WINDMILL', name: 'Meadow Windmill', color: 0xf5f0df, hardness: 999, preferredTool: 'HAND', icon: '🌬️', category: 'building', isCustomMesh: 'windmill',
  },
  STONE_MONOLITH: {
    id: 'STONE_MONOLITH', name: 'Ancient Stone Monolith', color: 0x64748b, hardness: 999, preferredTool: 'HAND', icon: '🗿', category: 'decoration', isCustomMesh: 'monolith',
  },
  HAY_BALE: {
    id: 'HAY_BALE', name: 'Golden Hay Bale', color: 0xeab308, hardness: 0.8, preferredTool: 'AXE', icon: '🌾', category: 'decoration', isCustomMesh: 'hay_bale',
  },
  GAZEBO: {
    id: 'GAZEBO', name: 'Garden Gazebo', color: 0xf8fafc, hardness: 999, preferredTool: 'HAND', icon: '🏛️', category: 'building', isCustomMesh: 'gazebo',
  },
  STONE_WELL: {
    id: 'STONE_WELL', name: 'Village Wishing Well', color: 0x94a3b8, hardness: 999, preferredTool: 'HAND', icon: '🪣', category: 'decoration', isCustomMesh: 'well',
  },
  WOODEN_BRIDGE: {
    id: 'WOODEN_BRIDGE', name: 'Wooden Footbridge', color: 0x9a6a3a, hardness: 999, preferredTool: 'HAND', icon: '🌉', category: 'building', isCustomMesh: 'bridge',
  },
  MARKET_STALL: {
    id: 'MARKET_STALL', name: 'Striped Market Stall', color: 0xf97316, hardness: 999, preferredTool: 'HAND', icon: '🏪', category: 'building', isCustomMesh: 'market_stall',
  },
  CAMPFIRE: {
    id: 'CAMPFIRE', name: 'Cozy Campfire', color: 0xf97316, hardness: 999, preferredTool: 'HAND', icon: '🔥', category: 'decoration', lightEmission: 1, isCustomMesh: 'campfire',
  },
  GARDEN_ARCH: {
    id: 'GARDEN_ARCH', name: 'Flower Garden Arch', color: 0xec4899, hardness: 999, preferredTool: 'HAND', icon: '🌸', category: 'decoration', isCustomMesh: 'garden_arch',
  },
  TRAINING_DUMMY: {
    id: 'TRAINING_DUMMY', name: 'Combat Training Dummy', color: 0x92400e, hardness: 999, preferredTool: 'HAND', icon: '🎯', category: 'decoration', isCustomMesh: 'training_dummy',
  },
  FOUNTAIN: {
    id: 'FOUNTAIN', name: 'Town Fountain', color: 0x60a5fa, transparent: true, hardness: 999, preferredTool: 'HAND', icon: '⛲', category: 'decoration', isCustomMesh: 'fountain',
  },
};

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 'tool-1', name: 'Iron Pickaxe (Starter)', type: 'tool', toolType: 'PICKAXE', count: 1, icon: '⛏️', description: 'Free starter tool to mine stone, cobblestone, and ores.', power: 3 },
  { id: 'tool-2', name: 'Woodcutter Axe (Starter)', type: 'tool', toolType: 'AXE', count: 1, icon: '🪓', description: 'Free starter tool to chop timber logs and trees.', power: 3 },
  { id: 'tool-3', name: 'Garden Shovel (Starter)', type: 'tool', toolType: 'SHOVEL', count: 1, icon: '🛠️', description: 'Free starter tool to dig dirt, sand, and buried treasure chests.', power: 3 },
  { id: 'tool-4', name: 'Fighter Sword (Starter)', type: 'tool', toolType: 'SWORD', count: 1, icon: '⚔️', description: 'Free starter sword to slice monsters in Fighting Mode.', power: 3 },
  { id: 'tool-5', name: 'Fishing Rod (Starter)', type: 'tool', count: 1, icon: '🎣', description: 'Free starter fishing rod to catch salmon in ocean waters.', power: 3 },
  { id: 'block-1', name: 'Oak Timber Log', type: 'block', blockType: 'WOOD_LOG', count: 500, icon: '🪵', description: 'Sturdy wooden log for building structures & crafting.' },
  { id: 'block-2', name: 'Village Cobblestone', type: 'block', blockType: 'COBBLESTONE', count: 500, icon: '🧱', description: 'Standard village paving stone.' },
  { id: 'block-3', name: 'Wooden Planks', type: 'block', blockType: 'PLANKS', count: 500, icon: '🪚', description: 'Refined lumber for cozy flooring & chests.' },
  { id: 'ore-1', name: 'Black Coal Deposit', type: 'block', blockType: 'COAL_ORE', count: 500, icon: '⬛', description: 'Free coal deposit for smelting bars.' },
  { id: 'ore-2', name: 'Rich Iron Vein', type: 'block', blockType: 'IRON_ORE', count: 500, icon: '🪨', description: 'Free iron ore for forging tools & swords.' },
  { id: 'ore-3', name: 'Glittering Gold Ore', type: 'block', blockType: 'GOLD_ORE', count: 500, icon: '✨', description: 'Free gold ore for smelting gold bars.' },
  { id: 'ore-4', name: 'Glowing Mana Crystal', type: 'block', blockType: 'CRYSTAL_ORE', count: 500, icon: '💎', description: 'Free mana crystal for magical recipes.' },
  { id: 'herb-1', name: 'Healing Wild Herb', type: 'block', blockType: 'HERB', count: 200, icon: '🌿', description: 'Free wild herb for potions & cooking.' },
  { id: 'berry-1', name: 'Wild Berry Bush', type: 'block', blockType: 'BERRY_BUSH', count: 200, icon: '🍓', description: 'Free wild berries for baking pies.' },
  { id: 'shroom-1', name: 'Red Cap Mushroom', type: 'block', blockType: 'MUSHROOM', count: 200, icon: '🍄', description: 'Free mushroom for cooking stews.' },
  { id: 'fish-1', name: 'Fresh Fish', type: 'consumable', count: 100, icon: '🐟', description: 'Freshly caught fish! Eat to restore 40 HP & 50 Stamina.' },
  { id: 'crop-1', name: 'Wheat Wheatland', type: 'block', blockType: 'CROPS', count: 200, icon: '🌾', description: 'Free wheat crops for cooking.' },
  { id: 'block-4', name: 'Beige House Wall', type: 'block', blockType: 'WALL_BEIGE', count: 50, icon: '🏠', description: 'Warm beige stucco for traditional houses.' },
  { id: 'block-5', name: 'Brown Shingle Roof', type: 'block', blockType: 'ROOF_BROWN', count: 50, icon: '⛺', description: 'Classic angled brown roof tile.' },
  { id: 'block-6', name: 'Wooden Fence', type: 'block', blockType: 'FENCE', count: 50, icon: '🚧', description: 'Keeps farm animals and monsters out.' },
  { id: 'block-7', name: 'Village Lantern', type: 'block', blockType: 'LAMP', count: 30, icon: '🏮', description: 'Casts a warm glowing light at night.' },
  { id: 'structure-pond', name: 'Lily Pond Kit', type: 'block', blockType: 'SMALL_POND', count: 10, icon: '🪷', description: 'Place a peaceful little pond with lily pads.' },
  { id: 'structure-ring', name: 'Open-Air Boxing Ring', type: 'block', blockType: 'BOXING_RING', count: 10, icon: '🥊', description: 'A standalone ring for friendly matches.' },
  { id: 'structure-well', name: 'Village Wishing Well', type: 'block', blockType: 'STONE_WELL', count: 10, icon: '🪣', description: 'A classic stone well for a village square.' },
  { id: 'structure-gazebo', name: 'Garden Gazebo', type: 'block', blockType: 'GAZEBO', count: 10, icon: '🏛️', description: 'An open garden shelter for gathering.' },
  { id: 'structure-windmill', name: 'Meadow Windmill', type: 'block', blockType: 'WINDMILL', count: 10, icon: '🌬️', description: 'A tall windmill landmark for farm fields.' },
  { id: 'structure-stall', name: 'Striped Market Stall', type: 'block', blockType: 'MARKET_STALL', count: 10, icon: '🏪', description: 'A cozy open-air market stand.' },
  { id: 'structure-bridge', name: 'Wooden Footbridge', type: 'block', blockType: 'WOODEN_BRIDGE', count: 10, icon: '🌉', description: 'A short bridge for ponds and streams.' },
  { id: 'structure-fountain', name: 'Town Fountain', type: 'block', blockType: 'FOUNTAIN', count: 10, icon: '⛲', description: 'A water feature for plazas and gardens.' },
  { id: 'structure-arch', name: 'Flower Garden Arch', type: 'block', blockType: 'GARDEN_ARCH', count: 10, icon: '🌸', description: 'A charming entrance for a garden path.' },
  { id: 'structure-dummy', name: 'Combat Training Dummy', type: 'block', blockType: 'TRAINING_DUMMY', count: 10, icon: '🎯', description: 'A practice target for a training yard.' },
  { id: 'structure-campfire', name: 'Cozy Campfire', type: 'block', blockType: 'CAMPFIRE', count: 10, icon: '🔥', description: 'A warm campfire for wilderness rest stops.' },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest-wagon',
    title: 'The Broken Wagon Incident',
    summary: 'A merchant wagon crashed on the forest road! Detective Barnaby cordoned off the scene with yellow caution tape. Inspect the scene and gather lumber to repair the wagon.',
    giverNpcId: 'npc-barnaby',
    giverName: 'Detective Barnaby',
    status: 'active',
    objectives: [
      { id: 'obj-inspect', description: 'Inspect the covered wagon crime scene', current: 0, target: 1, type: 'inspect', targetId: 'wagon-scene' },
      { id: 'obj-logs', description: 'Mine or provide Oak Timber Logs', current: 0, target: 5, type: 'mine', targetId: 'WOOD_LOG' },
    ],
    rewardGold: 150,
    rewardExp: 350,
    rewardItem: { id: 'reward-1', name: 'Sheriff Badge Hat', count: 1, icon: '🤠' },
  },
  {
    id: 'quest-square',
    title: 'Village Square Defense',
    summary: 'Elder Thorne has called a council meeting at the wooden table in the square. The village needs a cobblestone perimeter to protect from nighttime slimes.',
    giverNpcId: 'npc-thorne',
    giverName: 'Elder Thorne',
    status: 'available',
    objectives: [
      { id: 'obj-talk-thorne', description: 'Speak with Elder Thorne at the town table', current: 0, target: 1, type: 'talk', targetId: 'npc-thorne' },
      { id: 'obj-place-cobble', description: 'Place Cobblestone blocks in the village', current: 0, target: 10, type: 'build', targetId: 'COBBLESTONE' },
    ],
    rewardGold: 200,
    rewardExp: 500,
    rewardItem: { id: 'reward-2', name: 'Golden Pickaxe', count: 1, icon: '✨' },
  },
  {
    id: 'quest-cottage',
    title: 'Cozy Homesteading',
    summary: 'Build your very own beige cottage with a brown roof near the riverbank!',
    giverNpcId: 'npc-lyra',
    giverName: 'Merchant Lyra',
    status: 'available',
    objectives: [
      { id: 'obj-build-wall', description: 'Place Beige House Wall blocks', current: 0, target: 8, type: 'build', targetId: 'WALL_BEIGE' },
      { id: 'obj-build-roof', description: 'Place Brown Shingle Roof blocks', current: 0, target: 4, type: 'build', targetId: 'ROOF_BROWN' },
    ],
    rewardGold: 300,
    rewardExp: 600,
    rewardItem: { id: 'reward-3', name: 'Village Lanterns', count: 4, icon: '🏮' },
  },
];
export const INITIAL_NPCS: NPC[] = [
  {
    id: 'npc-finn',
    name: 'Finn',
    title: 'Pond Keeper',
    x: -18,
    y: 2,
    z: 18,
    rotation: 0.4,
    headStyle: 'detective',
    outfitColor: '#1d4ed8',
    hairColor: '#8b5a2b',
    level: 2,
    dialogue: {
      greeting: 'The pond is calm today. Want to fish?',
      options: [
        { text: 'Tell me about this place', response: 'This little pond is a quiet place to catch fish and restore your strength.' },
      ],
    },
    statusBubble: 'Pond',
  },
  {
    id: 'npc-cole',
    name: 'Cole',
    title: 'Coal House Foreman',
    x: 22,
    y: 2,
    z: -18,
    rotation: -0.6,
    headStyle: 'blacksmith',
    outfitColor: '#334155',
    hairColor: '#4b5563',
    level: 3,
    dialogue: {
      greeting: 'Coal is the lifeblood of the village. Want to mine some?',
      options: [
        { text: 'Show me the coal house', response: 'Inside the stone shed you can haul out coal lumps and refill your stamina.' },
      ],
    },
    statusBubble: 'Coal House',
  },
  {
    id: 'npc-rocky',
    name: 'Rocky',
    title: 'Ringmaster',
    x: -22,
    y: 2,
    z: -18,
    rotation: 1.2,
    headStyle: 'guard',
    outfitColor: '#7f1d1d',
    hairColor: '#111827',
    level: 3,
    dialogue: {
      greeting: 'Step into the ring if you want a real fight.',
      options: [
        { text: 'Challenge the champion', response: 'A fee gets you a match and a chance at the prize purse.' },
      ],
    },
    statusBubble: 'Boxing Ring',
  },
  {
    id: 'npc-buster',
    name: 'Buster',
    title: 'Roadside Boxer',
    x: -90,
    y: 2,
    z: 70,
    rotation: 0.7,
    headStyle: 'guard',
    outfitColor: '#7f1d1d',
    hairColor: '#475569',
    level: 6,
    dialogue: {
      greeting: 'Bring me coal and iron ores! I forge swords, shields, and tools.',
      options: [
        { text: 'Open Forge', response: 'Use Forge & Craft to smelt bars and upgrade gear!' },
      ],
    },
    statusBubble: '⚒️ Blacksmith Forge',
  },

  {
    id: 'npc-farmer',
    name: 'Farmer Barnaby 👨‍🌾',
    title: 'Village Farmer',
    x: 120,
    y: 2,
    z: 120,
    rotation: 0.5,
    headStyle: 'villager',
    outfitColor: '#15803d',
    hairColor: '#b45309',
    level: 3,
    dialogue: {
      greeting: 'Welcome to the farm! Feed the cows or harvest fresh wheat.',
      options: [
        { text: 'Harvest Crops', response: 'Take a shovel and harvest wheat and carrots!' },
      ],
    },
    statusBubble: '👨‍🌾 Cow Farm',
  },
  {
    id: 'npc-finn',
    name: 'Fisherman Finn 🎣',
    title: 'Master Angler',
    x: -130,
    y: 2,
    z: 120,
    rotation: 0,
    headStyle: 'villager',
    outfitColor: '#0284c7',
    hairColor: '#f59e0b',
    level: 5,
    dialogue: {
      greeting: 'The lake is full of fresh salmon today! Need a fishing rod?',
      options: [
        { text: 'Cast Fishing Line', response: 'Left-click water edge to reel in fresh fish!' },
      ],
    },
    statusBubble: '🎣 Fishing Lake',
  },
  {
    id: 'npc-chef',
    name: 'Chef Pierre 👩‍🍳',
    title: 'Master Chef',
    x: -90,
    y: 2,
    z: 90,
    rotation: -1.2,
    headStyle: 'villager',
    outfitColor: '#f8fafc',
    hairColor: '#0f172a',
    level: 4,
    dialogue: {
      greeting: 'Bon appétit! I cook fish meals and mushroom stews outside the restaurant.',
      options: [
        { text: 'View Recipes', response: 'Open Forge & Craft menu to cook delicious meals!' },
      ],
    },
    statusBubble: '🍲 Restaurant & Bakery',
  },
  {
    id: 'npc-cole',
    name: 'Blacksmith Cole ⚒️',
    title: 'Master Blacksmith',
    x: -100,
    y: 2,
    z: -100,
    rotation: 1.5,
    headStyle: 'villager',
    outfitColor: '#334155',
    hairColor: '#475569',
    level: 6,
    dialogue: {
      greeting: 'Bring me coal and iron ores! I forge swords, shields, and tools.',
      options: [
        { text: 'Open Forge', response: 'Use Forge & Craft to smelt bars and upgrade gear!' },
      ],
    },
    statusBubble: '⚒️ Blacksmith Forge',
  },
  {
    id: 'npc-wizard',
    name: 'Wizard Gandalf 🧙',
    title: 'High Mage',
    x: 200,
    y: 2,
    z: 200,
    rotation: -0.5,
    headStyle: 'wizard',
    outfitColor: '#7c3aed',
    hairColor: '#cbd5e1',
    level: 10,
    dialogue: {
      greeting: 'Ah, young adventurer! Do you seek glowing mana crystals and potions?',
      options: [
        { text: 'Learn Magic', response: 'Brew wild herbs and crystals into glowing health potions.' },
      ],
    },
    statusBubble: '🧙 Crystal Cavern',
  },
  {
    id: 'npc-elder',
    name: 'Village Elder 🧓',
    title: 'Town Elder',
    x: 0,
    y: 2,
    z: -10,
    rotation: 0,
    headStyle: 'villager',
    outfitColor: '#92400e',
    hairColor: '#f1f5f9',
    level: 8,
    dialogue: {
      greeting: 'Welcome to Voxelverse! Complete daily tasks to earn gold and level up.',
      options: [
        { text: 'Town Lore', response: 'Our island is rich in lumber, minerals, and wild animals.' },
      ],
    },
    statusBubble: '🧓 Town Square',
  },
  {
    id: 'npc-guard',
    name: 'Guard Marcus 👮',
    title: 'Town Gatekeeper',
    x: 10,
    y: 2,
    z: 40,
    rotation: 0.8,
    headStyle: 'guard',
    outfitColor: '#1e3a8a',
    hairColor: '#1e293b',
    level: 7,
    dialogue: {
      greeting: 'I patrol the streets to keep monsters out of the village.',
      options: [
        { text: 'Report Monsters', response: 'Switch to Fighting Mode to defeat wilderness beasts!' },
      ],
    },
    statusBubble: '👮 Gatekeeper Patrol',
  },
  {
    id: 'npc-merchant',
    name: 'Travelling Merchant 🛒',
    title: 'Wandering Trader',
    x: 120,
    y: 2,
    z: -140,
    rotation: -0.7,
    headStyle: 'merchant',
    outfitColor: '#d97706',
    hairColor: '#78350f',
    level: 5,
    dialogue: {
      greeting: 'Rare items for sale! Sell me your gold, coal, and fish for high prices.',
      options: [
        { text: 'Trade Goods', response: 'Open Inventory to sell your harvested resources for Gold!' },
      ],
    },
    statusBubble: '🛒 General Store & Fair',
  },
  {
    id: 'npc-ruby',
    name: 'Jeweller Ruby 💎',
    title: 'Gems & Jewels Broker',
    x: -90,
    y: 2,
    z: -120,
    rotation: 0.2,
    headStyle: 'merchant',
    outfitColor: '#fda4af',
    hairColor: '#7c2d12',
    level: 4,
    dialogue: {
      greeting: 'I buy glittering gold ores and polished mana crystals.',
      options: [
        { text: 'Sell Gold & Gems', response: 'Sell gold bars and crystals for thousands of Gold!' },
      ],
    },
    statusBubble: '💎 Jeweller Shop',
  },
  {
    id: 'npc-stable',
    name: 'Stable Master Jack 🐎',
    title: 'Equestrian Trainer',
    x: 100,
    y: 2,
    z: -100,
    rotation: -0.8,
    headStyle: 'villager',
    outfitColor: '#b45309',
    hairColor: '#92400e',
    level: 4,
    dialogue: {
      greeting: 'Our horses love fresh carrots! Visit the stable anytime.',
      options: [
        { text: 'Pet Horses', response: 'The horses are resting in their wooden stalls.' },
      ],
    },
    statusBubble: '🐎 Horse Stable',
  },
  {
    id: 'npc-explorer',
    name: 'Explorer Columbus 🗺️',
    title: 'Cavern Surveyor',
    x: -150,
    y: 2,
    z: -150,
    rotation: 1.1,
    headStyle: 'villager',
    outfitColor: '#065f46',
    hairColor: '#047857',
    level: 6,
    dialogue: {
      greeting: 'The mine entrance leads deep into the mountain. Have you found the treasure chests?',
      options: [
        { text: 'Discover Camps', response: 'Walk to wilderness camps to complete Pioneer Explorer quests!' },
      ],
    },
    statusBubble: '⛏️ Mine Entrance',
  },
  {
    id: 'npc-delivery',
    name: 'Postman Delivery 📦',
    title: 'Village Courier',
    x: -15,
    y: 2,
    z: -15,
    rotation: -0.4,
    headStyle: 'villager',
    outfitColor: '#ea580c',
    hairColor: '#c2410c',
    level: 3,
    dialogue: {
      greeting: 'Special packages delivered across Voxelverse!',
      options: [
        { text: 'Check Mail', response: 'All village deliveries are running smoothly!' },
      ],
    },
    statusBubble: '📦 Post Office & Bank',
  },
];

export const CRAFTING_RECIPES: CraftingRecipe[] = [
  // Smelting
  {
    id: 'smelt-iron',
    name: 'Iron Bar',
    icon: '🧱',
    category: 'smelting',
    description: 'Smelt 2 Iron Ores and 1 Coal into a solid Iron Bar ($60 value).',
    ingredients: [
      { name: 'Rich Iron Vein', icon: '🪨', count: 2 },
      { name: 'Black Coal Deposit', icon: '⬛', count: 1 },
    ],
    result: { name: 'Iron Bar', icon: '🧱', count: 1 },
  },
  {
    id: 'smelt-gold',
    name: 'Gold Bar',
    icon: '✨',
    category: 'smelting',
    description: 'Smelt 2 Gold Ores and 1 Coal into a pure Gold Bar ($120 value).',
    ingredients: [
      { name: 'Glittering Gold Ore', icon: '✨', count: 2 },
      { name: 'Black Coal Deposit', icon: '⬛', count: 1 },
    ],
    result: { name: 'Gold Bar', icon: '✨', count: 1 },
  },
  {
    id: 'smelt-crystal',
    name: 'Refined Mana Crystal',
    icon: '💎',
    category: 'smelting',
    description: 'Refine 2 Mana Crystals into a glowing magical gem ($180 value).',
    ingredients: [
      { name: 'Glowing Mana Crystal', icon: '💎', count: 2 },
    ],
    result: { name: 'Refined Mana Crystal', icon: '💎', count: 1 },
  },

  // Tools & Upgrade
  {
    id: 'craft-iron-pickaxe',
    name: 'Iron Pickaxe Upgrade',
    icon: '⛏️',
    category: 'tools',
    description: 'Forge a heavy Iron Pickaxe for fast ore extraction (Power +5).',
    ingredients: [
      { name: 'Iron Bar', icon: '🧱', count: 2 },
      { name: 'Oak Timber Log', icon: '🪵', count: 2 },
    ],
    result: { name: 'Iron Pickaxe', icon: '⛏️', count: 1 },
  },
  {
    id: 'craft-axe',
    name: 'Steel Woodcutter Axe',
    icon: '🪓',
    category: 'tools',
    description: 'Sharp steel axe to slice through timber trees instantly.',
    ingredients: [
      { name: 'Iron Bar', icon: '🧱', count: 2 },
      { name: 'Oak Timber Log', icon: '🪵', count: 2 },
    ],
    result: { name: 'Woodcutter Axe', icon: '🪓', count: 1 },
  },

  // Weapons & Armor
  {
    id: 'craft-sword',
    name: 'Steel Fighter Sword',
    icon: '⚔️',
    category: 'weapons',
    description: 'Double-edged steel blade to slice monsters with high damage (+30 DMG).',
    ingredients: [
      { name: 'Iron Bar', icon: '🧱', count: 3 },
      { name: 'Oak Timber Log', icon: '🪵', count: 1 },
    ],
    result: { name: 'Steel Fighter Sword', icon: '⚔️', count: 1 },
  },
  {
    id: 'craft-shield',
    name: 'Knight Wooden Shield',
    icon: '🛡️',
    category: 'weapons',
    description: 'Sturdy oak shield reinforced with iron trim to block monster attacks.',
    ingredients: [
      { name: 'Wooden Planks', icon: '🪚', count: 4 },
      { name: 'Iron Bar', icon: '🧱', count: 1 },
    ],
    result: { name: 'Knight Wooden Shield', icon: '🛡️', count: 1 },
  },
  {
    id: 'craft-bow',
    name: 'Hunting Longbow',
    icon: '🏹',
    category: 'weapons',
    description: 'Crafted longbow strung with herbal sinew for hunting wild game.',
    ingredients: [
      { name: 'Oak Timber Log', icon: '🪵', count: 3 },
      { name: 'Healing Wild Herb', icon: '🌿', count: 2 },
    ],
    result: { name: 'Hunting Longbow', icon: '🏹', count: 1 },
  },

  // Cooking & Brewing
  {
    id: 'cook-fish',
    name: 'Grilled Salmon Meal',
    icon: '🐟',
    category: 'cooking',
    description: 'Grill fresh caught river fish over a bonfire (+60 HP).',
    ingredients: [
      { name: 'Healing Wild Herb', icon: '🌿', count: 1 },
      { name: 'Oak Timber Log', icon: '🪵', count: 1 },
    ],
    result: { name: 'Grilled Salmon Meal', icon: '🐟', count: 1 },
  },
  {
    id: 'cook-stew',
    name: 'Hearty Mushroom Stew',
    icon: '🍲',
    category: 'cooking',
    description: 'Simmer red cap mushrooms and wheat crops into a savory stew (+80 HP).',
    ingredients: [
      { name: 'Red Cap Mushroom', icon: '🍄', count: 2 },
      { name: 'Wheat Wheatland', icon: '🌾', count: 1 },
    ],
    result: { name: 'Hearty Mushroom Stew', icon: '🍲', count: 1 },
  },
  {
    id: 'brew-potion',
    name: 'Greater Health Potion',
    icon: '🧪',
    category: 'brewing',
    description: 'Brew wild herbs and red berries into a glowing health potion.',
    ingredients: [
      { name: 'Healing Wild Herb', icon: '🌿', count: 2 },
      { name: 'Wild Berry Bush', icon: '🍓', count: 1 },
    ],
    result: { name: 'Greater Health Potion', icon: '🧪', count: 1 },
  },

  // Building & Structures
  {
    id: 'build-campfire',
    name: 'Wilderness Campfire',
    icon: '🔥',
    category: 'building',
    description: 'Build a cozy campfire to cook meals, warm up, and light the night.',
    ingredients: [
      { name: 'Oak Timber Log', icon: '🪵', count: 4 },
      { name: 'Village Cobblestone', icon: '🧱', count: 2 },
    ],
    result: { name: 'Wilderness Campfire', icon: '🔥', count: 1, blockType: 'LAMP' },
  },
  {
    id: 'build-chest',
    name: 'Wooden Storage Chest',
    icon: '📦',
    category: 'building',
    description: 'Build a storage chest to store your gathered ores and precious loot.',
    ingredients: [
      { name: 'Wooden Planks', icon: '🪚', count: 8 },
    ],
    result: { name: 'Wooden Storage Chest', icon: '📦', count: 1, blockType: 'TABLE_WOOD' },
  },
];

export const INITIAL_DAILY_QUESTS: DailyQuest[] = [
  {
    id: 'daily-chop',
    title: 'Timber Logger',
    summary: 'Chop 2 trees and logs across the forest for a quick bounty.',
    icon: '🪓',
    category: 'chop',
    current: 0,
    target: 5,
    rewardGold: 1500,
    rewardExp: 200,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Walk over to any forest area using WASD (look for 🪵 Oak Tree floating labels).',
      '2. Make sure your free Woodcutter Axe (Starter) is selected from your hotbar.',
      '3. Stand close to the tree trunk and Left-Click to chop 2 timber logs!',
    ],
  },
  {
    id: 'daily-mine',
    title: 'Deep Vein Mining',
    summary: 'Mine 2 stone, coal, iron, gold, or crystal ores in the mountain mines.',
    icon: '⛏️',
    category: 'mine',
    current: 0,
    target: 2,
    rewardGold: 2500,
    rewardExp: 300,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Explore mountain mines & caverns to find 🪨 Stone, ⬛ Coal, 🪨 Iron, ✨ Gold, or 💎 Mana Crystals.',
      '2. Select your free Iron Pickaxe (Starter) from your inventory.',
      '3. Stand close to the rock or ore block and Left-Click to mine 2 ores!',
    ],
  },
  {
    id: 'daily-fish',
    title: 'Master Angler',
    summary: 'Catch 1 fresh salmon from the ocean water edge.',
    icon: '🎣',
    category: 'fish',
    current: 0,
    target: 1,
    rewardGold: 1800,
    rewardExp: 250,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Walk over to the edge of the blue ocean water surrounding the island continent.',
      '2. Select your free Fishing Rod (Starter) from your inventory hotbar.',
      '3. Left-Click directly on the water edge to cast your fishing line and catch 1 fresh salmon!',
    ],
  },
  {
    id: 'daily-cook',
    title: 'Master Chef',
    summary: 'Cook 1 delicious meal or fish over campfires.',
    icon: '🍲',
    category: 'cook',
    current: 0,
    target: 1,
    rewardGold: 2000,
    rewardExp: 250,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Click on the 🛠️ Forge & Craft button in the top header menu.',
      '2. Click on the 🍲 Cooking tab to view recipes like Grilled Salmon Meal & Mushroom Stew.',
      '3. Gather fresh fish, herbs & mushrooms, then click "Craft" to cook 1 meal!',
    ],
  },
  {
    id: 'daily-craft',
    title: 'Blacksmith Artisan',
    summary: 'Craft 1 tool, weapon, armor bar, or camp structure at the forge.',
    icon: '🛠️',
    category: 'craft',
    current: 0,
    target: 1,
    rewardGold: 2200,
    rewardExp: 300,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Mine ores & coal or chop wood logs around the map.',
      '2. Open the 🛠️ Forge & Craft modal from the top header menu.',
      '3. Select any Smelting, Tools, or Weapons recipe and click "Craft" to forge 1 item!',
    ],
  },
  {
    id: 'daily-monsters',
    title: 'Monster Slayer',
    summary: 'Defeat 2 wolves, bears, goblins, or zombies in Fighting Mode.',
    icon: '⚔️',
    category: 'monsters',
    current: 0,
    target: 2,
    rewardGold: 5000,
    rewardExp: 500,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Switch to ⚔️ Fighting Mode using the top-right mode selector toggle.',
      '2. A horde of Dire Wolves, Grizzly Bears, Goblins, & Zombies will march towards you.',
      '3. Press [P] on your keyboard or click the SLICE ZOMBIES button to slay 2 monsters!',
    ],
  },
  {
    id: 'daily-explore',
    title: 'Pioneer Explorer',
    summary: 'Explore 1 wilderness location, monster camp, or crystal cave at your own pace.',
    icon: '🗺️',
    category: 'explore',
    current: 0,
    target: 1,
    rewardGold: 3000,
    rewardExp: 400,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Walk towards the outer wilderness regions of the map using WASD.',
      '2. Locate Monster Camps (campfires & barricades), Crystal Caverns, or Buried Treasure Chests.',
      '3. Walk within 8 blocks of 1 location to complete exploration!',
    ],
  },
  {
    id: 'daily-gold',
    title: 'Merchant Tycoon',
    summary: 'Sell resources or items worth 25 Gold to shop merchants.',
    icon: '💰',
    category: 'gold',
    current: 0,
    target: 25,
    rewardGold: 4000,
    rewardExp: 600,
    completed: false,
    claimed: false,
    guideSteps: [
      '1. Gather valuable Gold Ores, Mana Crystals, Coal, or cook Gourmet Meals.',
      '2. Speak with merchant NPCs in the village square or open your inventory.',
      '3. Sell your harvested items to shop merchants to accumulate 25 Gold!',
    ],
  },
];
